/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  kotlin("jvm")
}

group = "net.kigawa"
version = "1.0.0"

repositories {
  mavenLocal()
  mavenCentral()
  maven {
    url = uri("https://repo.maven.apache.org/maven2/")
  }

  maven {
    url = uri("https://repo.papermc.io/repository/maven-public/")
  }

  maven {
    url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
  }

  maven {
    url = uri("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
  }
}

dependencies {
}